{% set name = "tango-starter" %}
{% set version = "8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/starter/-/archive/Starter-{{ version }}/starter-Starter-{{ version }}.tar.gz
  sha256: b8c04d333e76ce280769a7f027469a3542e8b6cf427ab9513741561743b2272e
  patches:
    - find-zeromq-win.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - libtool                 # [unix]
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # Starter --help returns 255
    - Starter --help 2>&1 | grep usage         # [unix]
    - Starter.exe --help 2>&1 | findstr usage  # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Device server to control Tango components
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This device server is able to control Tango components (database, device servers, clients...).
    It is able to start or stop and to report the status of these components.
  dev_url: https://gitlab.com/tango-controls/starter

extra:
  recipe-maintainers:
    - beenje
